local DrRayLibrary = loadstring(game:HttpGet("https://raw.githubusercontent.com/ArceusXArchivezx/Nekoi/refs/heads/main/%E9%9F%93%E5%9B%BD%E3%81%A7%E7%BE%8E%E5%91%B3%E3%81%97%E3%81%84%E9%A3%9F%E3%81%B9%E7%89%A9%E3%81%AF%E4%BD%95%E3%81%A7%E3%81%99%E3%81%8B%EF%BC%9F"))()
local window = DrRayLibrary:Load("King", "Default")

local tab = DrRayLibrary.newTab("Menu", "ImageIdHere")

tab.newLabel("Menu - Fly Player")
tab.newButton("Fly Player", "Prints Hello!", function()
    loadstring(game:HttpGet('https://pastebin.com/raw/HKPm33Pq'))()
end)

tab.newLabel("Menu - f3x")
tab.newButton("f3x", "Hi!", function()
    loadstring(game:GetObjects("rbxassetid://6695644299")[1].Source)()
end)

tab.newLabel("Menu - AutoPlay Player")
tab.newButton("AutoPlay Player", "Hi!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/AzureNeoX/Autoplay/refs/heads/main/Q",true))()
end)

tab.newLabel("Menu - Teleport Tool Player")
tab.newButton("Teleport Tool Player", "Hi!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/AzureNeoX/Teleport-Tool/refs/heads/main/Q", true))()
end)

tab.newLabel("Menu - Sigma Spy")
tab.newButton("Sigma Spy", "Hi!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/depthso/Sigma-Spy/refs/heads/main/Main.lua"))()
end)

tab.newLabel("Menu - Simple Spy Mobile")
tab.newButton("Simple Spy Mobile", "Hi!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wfrefdewwss/Discord-Custom-Status-24-7/refs/heads/main/requirements.txt"))()
end)

tab.newLabel("Menu - Infinite Yield")
tab.newButton("Infinite Yield", "Hi!", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)

tab.newLabel("Menu - Octo Spy")
tab.newButton("Octo Spy", "Hi!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/InfernusScripts/Octo-Spy/refs/heads/main/Main.lua", true))()
end)

tab.newLabel("Menu - Hydroxide")
tab.newButton("Hydroxide", "Hi!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/%s/Hydroxide/%s/%s.lua", true))()
end)

tab.newLabel("Menu - Delete Tool")
tab.newButton("Delete Tool", "Hi!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Gamez635/NameScript/refs/heads/main/Delete%20Tool.lua", true))()
end)

tab.newLabel("Menu - Btools Advanced")
tab.newButton("Btools Advanced", "Hi!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Gamez635/NameScript/refs/heads/main/Btools%20Advanced.lua", true))()
end)

tab.newLabel("Menu - Chat Logger")
tab.newButton("Chat Logger", "Hi!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Gamez635/NameScript/refs/heads/main/Chat%20Spy.lua", true))()
end)

tab.newLabel("Menu - Explorer")
tab.newButton("Explorer", "Hi!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Gamez635/NameScript/refs/heads/main/Explorer.lua", true))()
end)

tab.newLabel("Menu - Property Viewer")
tab.newButton("Property Viewer", "Hi!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Gamez635/NameScript/refs/heads/main/Property%20Viewer.luau", true))()
end)

tab.newLabel("Menu - Hook Remote Caller")
tab.newButton("Hook Remote Caller", "Hi!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Gamez635/NameScript/refs/heads/main/Hook%20Remote%20Caller.luau", true))()
end)

tab.newLabel("Menu - Function Hooking")
tab.newButton("Function Hooking", "Hi!", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Gamez635/NameScript/refs/heads/main/Function%20Hooking.luau", true))()
end)

tab.newLabel("")
tab.newButton("", "Hi!", function()
    print('Hello!')
end)

tab.newLabel("")
tab.newButton("", "Hi!", function()
    print('Hello!')
end)

tab.newLabel("")
tab.newButton("", "Hi!", function()
    print('Hello!')
end)

tab.newLabel("")
tab.newButton("", "Hi!", function()
    print('Hello!')
end)
